import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import { ShoppingCartContextProvider } from "@/context/ShoppingCartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ShoppingCartContextProvider>
          <MainLayout>{children}</MainLayout>
        </ShoppingCartContextProvider>
      </body>
    </html>
  );
}
